-- Sistema para Loja de Aluguel e Venda de Produtos para Festas


-- *************************************  CRIANDO TABELAS   *************************************
CREATE TABLE CATEGORIA_CLIENTE(
	codigoCategoria INT NOT NULL PRIMARY KEY,
	descricao VARCHAR2(50),
	diasDeEmprestimo INT NOT NULL
);

CREATE SEQUENCE CATEGORIA_CLIENTE_SEQUENCIA
INCREMENT BY 1
START WITH 1
MAXVALUE 99999
NOCYCLE; 
---------------------------------------

CREATE TABLE CATEGORIA_PRODUTO(
  idCategoriaProduto INT NOT NULL PRIMARY KEY,
  descricao VARCHAR2(50)
);

CREATE SEQUENCE CATEGORIA_PRODUTO_SEQUENCIA
INCREMENT BY 1
START WITH 1
MAXVALUE 99999
NOCYCLE; 
---------------------------------------
CREATE TABLE CLIENTE(
  cpfCliente VARCHAR2(20) NOT NULL , 
  nomeCliente VARCHAR2(50) NOT NULL,
  enderecoCliente VARCHAR2(80) NOT NULL,
  cidadeCliente VARCHAR2(30) NOT NULL,
  estadoCliente VARCHAR2(20) NOT NULL,
  telefoneCliente VARCHAR2(15) NOT NULL,
  emailCliente VARCHAR2(50),
  codigoCategoria INT NOT NULL,
  CLIENTE_DATA_NASCIMENTO DATE,
  PRIMARY KEY(cpfCliente), 
  FOREIGN KEY (codigoCategoria) REFERENCES CATEGORIA_CLIENTE(codigoCategoria) ON DELETE SET NULL
);


CREATE SEQUENCE CLIENTE_SEQUENCIA
INCREMENT BY 1
START WITH 1
MAXVALUE 99999
NOCYCLE;
-------------------------------------------------------------------
CREATE TABLE FORNECEDOR(
  CNPJ VARCHAR2(12) NOT NULL PRIMARY KEY,
  idProduto INT NOT NULL,
  nomeFornecedor VARCHAR2(80),
  enderecoFornecedor VARCHAR2(100),
  cidadeFornecedor VARCHAR2(100),
  estadoFornecedor VARCHAR2(80),
  emailFornecedor VARCHAR2(40),
  telefoneFornecedor VARCHAR2(15),
  FOREIGN KEY (idProduto) REFERENCES PRODUTO(idProduto) 
);

CREATE SEQUENCE FORNECEDOR_SEQUENCIA
INCREMENT BY 1
START WITH 1
MAXVALUE 99999
NOCYCLE;
---------------------------------------------------------------------------------------------
CREATE TABLE PRODUTO(
  codigoDeBarras VARCHAR2(30),
  idProduto INT primary key,
  nomeProduto VARCHAR2(100),
  idCategoriaProduto INT NOT NULL,
  quantidadeEstoque INT NOT NULL,
  fabricante VARCHAR2(100),
  localizacaoPrateleira VARCHAR2(5),
  precoDiario NUMBER(8,2) NOT NULL,
  PROD_FORN_CNPJ VARCHAR2(15) NOT NULL,
  FOREIGN KEY (PROD_FORN_CNPJ) REFERENCES FORNECEDOR(CNPJ) ON DELETE SET NULL,
  FOREIGN KEY (idCategoriaProduto) REFERENCES CATEGORIA_PRODUTO(idCategoriaProduto) ON DELETE SET NULL
); 

CREATE SEQUENCE PRODUTO_SEQUENCIA
INCREMENT BY 1
START WITH 1
MAXVALUE 99999
NOCYCLE;
---------------------------------------
CREATE TABLE PRODUTO_FORNECEDOR(
  ID_PRODUTO INT NOT NULL,
  CNPJ_FORNECEDOR VARCHAR2(15) NOT NULL,
  QTD_PRODUTO_COMPRAR INT NOT NULL,
  DATA_COMPRA TIMESTAMP NOT NULL,
  PRECO_UNITARIO NUMERIC(8,2) NOT NULL, 
  PRIMARY KEY(CNPJ_FORNECEDOR,ID_PRODUTO),
  FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(idProduto) ON DELETE CASCADE,
  FOREIGN KEY (CNPJ_FORNECEDOR) REFERENCES FORNECEDOR(CNPJ) ON DELETE CASCADE
);

CREATE SEQUENCE PRODUTO_FORNECEDOR_SEQUENCIA
INCREMENT BY 1
START WITH 1
MAXVALUE 99999
NOCYCLE;
---------------------------------------
CREATE TABLE FUNCIONARIO(
  idFuncionario INT NOT NULL PRIMARY KEY,
  nomeFuncionario VARCHAR2(50),
  enderecoFuncionario VARCHAR2(50),
  telefoneFuncionario VARCHAR2(15),
  dataNascimentoFuncionario DATE
);

CREATE SEQUENCE FUNCIONARIO_SEQUENCIA
INCREMENT BY 1
START WITH 1
MAXVALUE 99999
NOCYCLE;  
---------------------------------------
CREATE TABLE RESERVA(
  idReserva INT NOT NULL PRIMARY KEY,
  DATA_HORA TIMESTAMP,
  cpfCliente VARCHAR2(20) NOT NULL,
  idProduto INT NOT NULL,
  idFuncionario INT NOT NULL,
  RESERVAR_QTD_PRODUTO INT NOT NULL, 
  FOREIGN KEY (cpfCliente) REFERENCES CLIENTE(cpfCliente) ON DELETE CASCADE,
  FOREIGN KEY (idProduto) REFERENCES PRODUTO(idProduto) ON DELETE CASCADE,
  FOREIGN KEY (idFuncionario) REFERENCES FUNCIONARIO(idFuncionario) ON DELETE SET NULL
);

CREATE SEQUENCE RESERVA_SEQUENCIA
INCREMENT BY 1
START WITH 1
MAXVALUE 99999
NOCYCLE;
---------------------------------------
CREATE TABLE EMPRESTIMO(
  idEmprestimo INT NOT NULL PRIMARY KEY,
  DATA_HORA_EMPRESTIMO DATE,
  dataPrevista DATE,
  cpfCliente VARCHAR2(20) NOT NULL,
  idFuncionario INT NOT NULL,
  EMPRESTIMO_ID_PRODUTO INT NOT NULL,  
  EMPRESTIMO_QTD_PRODUTO INT NOT NULL,
  EMP_VALOR NUMERIC(8,2) NOT NULL, 
  EMP_DESCONTO NUMERIC(4,2) NOT NULL, 
  FOREIGN KEY (cpfCliente) REFERENCES CLIENTE(cpfCliente) ON DELETE SET NULL,
  FOREIGN KEY (idFuncionario) REFERENCES FUNCIONARIO(idFuncionario) ON DELETE SET NULL,
  FOREIGN KEY (EMPRESTIMO_ID_PRODUTO) REFERENCES PRODUTO(idProduto) ON DELETE SET NULL
);

CREATE SEQUENCE EMPRESTIMO_SEQUENCIA
INCREMENT BY 1
START WITH 1
MAXVALUE 99999
NOCYCLE;
---------------------------------------
CREATE TABLE DEVOLUCAO(
  DEVOLUCAO_ID INT PRIMARY KEY,
  DATA_HORA_DEVOLUCAO DATE,
  DEVOLUCAO_COD_BARRAS VARCHAR2(30),
  DEVOLUCAO_ID_FUNCIONARIO INT,
  DEVOLUCAO_CLIENTE_CPF VARCHAR2(20) NOT NULL,
  SUSPENSO CHAR(1),
  FOREIGN KEY (DEVOLUCAO_ID_FUNCIONARIO) REFERENCES FUNCIONARIO (idFuncionario) ON DELETE CASCADE,
  FOREIGN KEY (DEVOLUCAO_CLIENTE_CPF) REFERENCES CLIENTE(cpfCliente) ON DELETE CASCADE
);

CREATE SEQUENCE DEVOLUCAO_SEQUENCIA
INCREMENT BY 1
START WITH 1
MAXVALUE 99999
NOCACHE
NOCYCLE;